
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import pos.LigacaoMySql;
import java.sql.*;


public class frm_Pos extends javax.swing.JFrame {

    DefaultListModel descricao=new DefaultListModel();
    DefaultListModel quantidade=new DefaultListModel();
    DefaultListModel preco=new DefaultListModel();
    DefaultListModel total=new DefaultListModel();
            
    float total_pedido=0;
    NumberFormat Moeda=NumberFormat.getCurrencyInstance();
    
            
    public frm_Pos() {
        initComponents();
        setLocationRelativeTo(null);
        Desabilita_Botoes();
        Desabilitar_Paineis();
        Habilita_Botoes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
         
        private void Desabilita_Botoes(){
            bt_adicionar.setEnabled(false);
            bt_menos.setEnabled(false);
            bt_quantidade.setEnabled(false);
            bt_remover.setEnabled(false);
            bt_pagamentos.setEnabled(false);
            bt_imprimir.setEnabled(false);
        }    
        private void Habilita_Botoes(){
            bt_adicionar.setEnabled(true);
            bt_menos.setEnabled(true);
            bt_quantidade.setEnabled(true);
            bt_remover.setEnabled(true);
            bt_pagamentos.setEnabled(true);
        }  
                
        private void Desabilitar_Paineis(){
            Component[] p1=jp_cafeteria.getComponents();
            Component[] p2=jp_pastelaria.getComponents();
            Component[] p3=jp_bebidas.getComponents();
            
            for(int i=0;i<p1.length;i++){
                p1[i].setEnabled(false);
                p2[i].setEnabled(false);
            }
            for(int i=0;i<p3.length;i++){
                p3[i].setEnabled(false);
            }  
        }
        
        private void Habilitar_Paineis(){
            Component[] p1=jp_cafeteria.getComponents();
            Component[] p2=jp_pastelaria.getComponents();
            Component[] p3=jp_bebidas.getComponents();
            
            for(int i=0;i<p1.length;i++){
                p1[i].setEnabled(true);
                p2[i].setEnabled(true);
            }
            for(int i=0;i<p3.length;i++){
                p3[i].setEnabled(true);
            }  
        }
            
        class Imprimir implements Printable{
        public int print(Graphics g, PageFormat f, int pageIndex){
            if(pageIndex==0){
                Font F1=new Font("Arial",Font.BOLD,14);
                Font F2=new Font("Arial",Font.PLAIN,10);
                Font F3=new Font("Arial",Font.PLAIN,6);
                
                g.setFont(F1);
                g.setColor(Color.blue);
                g.drawString("Paga Pouco, Lda",50,50);
                
                g.setFont(F2);
                g.setColor(Color.BLACK);
                g.drawString("Rua António Alves, 50.",50, 65);
                g.drawString("2150-050 Lisboa",50, 75);
                g.drawString("Email: pagapouco@gmail.com",50,85);
                g.drawString("NIF: 520123123",50,95);
                
                g.drawString("Descrição:", 50,110);
                g.drawString("Qtd:",120,110);
                g.drawString("Preço:",140, 110);
                g.drawString("Total",180,110);
                g.drawLine(50,115,200,115);
                
                int y=125;
                for(int i=0;i<descricao.getSize();i++){
                    g.drawString(descricao.getElementAt(i).toString(),
                            50,y);
                    g.drawString(quantidade.getElementAt(i).toString(),
                            120,y);
                    g.drawString(preco.getElementAt(i).toString(),
                            140,y);
                    g.drawString(total.getElementAt(i).toString(),
                            180,y);
                    y+=10;
                }
                g.drawLine(50,y,200,y);
                g.drawString("Total: "+lbl_total.getText(),50,y+10);
                g.drawString("Numerário: "+lbl_numerario.getText(),50,y+20);
                g.drawString("Troco: "+lbl_troco.getText(),50,y+30);
                
                g.setFont(F3);
                g.drawString("Obrigado, Volte Sempre!",50,y+40);
                
                Calendar C=new GregorianCalendar();
                int dia=C.get(Calendar.DAY_OF_MONTH);
                int mes=C.get(Calendar.MONTH)+1;
                int ano=C.get(Calendar.YEAR);
                
                int hora=C.get(Calendar.HOUR_OF_DAY);
                int minuto=C.get(Calendar.MINUTE);
                int segundo=C.get(Calendar.SECOND);
                
                g.drawString(dia+"/"+mes+"/"+ano+" - "+hora+":"+minuto+":"+segundo,50,60);
                
                return PAGE_EXISTS;
                }
            else 
                return NO_SUCH_PAGE;
                    
        }         
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jp_cafeteria = new javax.swing.JPanel();
        bt_cafe = new javax.swing.JLabel();
        bt_carioca = new javax.swing.JLabel();
        bt_capuccino = new javax.swing.JLabel();
        bt_descafeinado = new javax.swing.JLabel();
        bt_galao = new javax.swing.JLabel();
        bt_garoto = new javax.swing.JLabel();
        jp_pastelaria = new javax.swing.JPanel();
        bt_mista = new javax.swing.JLabel();
        bt_pizza = new javax.swing.JLabel();
        bt_salgado = new javax.swing.JLabel();
        bt_folhado = new javax.swing.JLabel();
        bt_sandes = new javax.swing.JLabel();
        jp_bebidas = new javax.swing.JPanel();
        bt_agua = new javax.swing.JLabel();
        bt_vinho = new javax.swing.JLabel();
        bt_cola = new javax.swing.JLabel();
        bt_sumo = new javax.swing.JLabel();
        bt_bolo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bt_adicionar = new javax.swing.JButton();
        bt_menos = new javax.swing.JButton();
        bt_quantidade = new javax.swing.JButton();
        bt_remover = new javax.swing.JButton();
        bt_pagamentos = new javax.swing.JButton();
        bt_imprimir = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lbl_pedido = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_descricao = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_qtd = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_preco = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_total = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        bt_novo = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_numerario = new javax.swing.JLabel();
        lbl_troco = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setResizable(false);

        jp_cafeteria.setBackground(new java.awt.Color(255, 255, 255));
        jp_cafeteria.setBorder(javax.swing.BorderFactory.createTitledBorder("Cafeteria"));

        bt_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cafe.gif"))); // NOI18N
        bt_cafe.setText("Café");
        bt_cafe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_cafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_cafeMouseReleased(evt);
            }
        });

        bt_carioca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_carioca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carioca.gif"))); // NOI18N
        bt_carioca.setText("Carioca");
        bt_carioca.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_carioca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_carioca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_carioca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_carioca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_cariocaMouseReleased(evt);
            }
        });

        bt_capuccino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_capuccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capucino.gif"))); // NOI18N
        bt_capuccino.setText("Capuccino");
        bt_capuccino.setToolTipText("");
        bt_capuccino.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_capuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_capuccino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_capuccino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_capuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_capuccinoMouseReleased(evt);
            }
        });

        bt_descafeinado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/descafeinado.gif"))); // NOI18N
        bt_descafeinado.setText("Descafeinado");
        bt_descafeinado.setToolTipText("");
        bt_descafeinado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_descafeinado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_descafeinado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_descafeinado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_descafeinadoMouseReleased(evt);
            }
        });

        bt_galao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_galao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/galao.gif"))); // NOI18N
        bt_galao.setText("Galão");
        bt_galao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_galao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_galao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_galao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_galao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_galaoMouseReleased(evt);
            }
        });

        bt_garoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_garoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/garoto.gif"))); // NOI18N
        bt_garoto.setText("Garoto");
        bt_garoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_garoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_garoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_garoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_garoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_garotoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jp_cafeteriaLayout = new javax.swing.GroupLayout(jp_cafeteria);
        jp_cafeteria.setLayout(jp_cafeteriaLayout);
        jp_cafeteriaLayout.setHorizontalGroup(
            jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cafeteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_carioca, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(bt_cafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_capuccino, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(bt_galao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_descafeinado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_garoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_cafeteriaLayout.setVerticalGroup(
            jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cafeteriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_descafeinado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_capuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cafeteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_garoto)
                        .addComponent(bt_galao))
                    .addComponent(bt_carioca, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jp_pastelaria.setBackground(new java.awt.Color(255, 255, 255));
        jp_pastelaria.setBorder(javax.swing.BorderFactory.createTitledBorder("Pastelaria"));

        bt_mista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_mista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_mista.setText("Mista");
        bt_mista.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_mista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_mista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_mista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_mista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_mistaMouseReleased(evt);
            }
        });

        bt_pizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_pizza.setText("Pizza");
        bt_pizza.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_pizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_pizza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_pizza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_pizzaMouseReleased(evt);
            }
        });

        bt_salgado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_salgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salgado.gif"))); // NOI18N
        bt_salgado.setText("Salgado");
        bt_salgado.setToolTipText("");
        bt_salgado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_salgado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_salgado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salgado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_salgado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_salgadoMouseReleased(evt);
            }
        });

        bt_folhado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_folhado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_folhado.setText("Folhado");
        bt_folhado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_folhado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_folhado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_folhado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_folhado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_folhadoMouseReleased(evt);
            }
        });

        bt_sandes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sandes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_sandes.setText("Sandes");
        bt_sandes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sandes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_sandes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sandes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_sandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_sandesMouseReleased(evt);
            }
        });

        jp_bebidas.setBackground(new java.awt.Color(255, 255, 255));
        jp_bebidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));
        jp_bebidas.setDoubleBuffered(false);

        bt_agua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_agua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agua.gif"))); // NOI18N
        bt_agua.setText("Água");
        bt_agua.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_agua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_agua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_agua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_agua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_aguaMouseReleased(evt);
            }
        });

        bt_vinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_vinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vinho.gif"))); // NOI18N
        bt_vinho.setText("Vinho");
        bt_vinho.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_vinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_vinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_vinho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_vinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_vinhoMouseReleased(evt);
            }
        });

        bt_cola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cola.gif"))); // NOI18N
        bt_cola.setText("Cola");
        bt_cola.setToolTipText("");
        bt_cola.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_cola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_colaMouseReleased(evt);
            }
        });

        bt_sumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sumo.gif"))); // NOI18N
        bt_sumo.setText("Sumo");
        bt_sumo.setToolTipText("");
        bt_sumo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_sumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_sumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_sumoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jp_bebidasLayout = new javax.swing.GroupLayout(jp_bebidas);
        jp_bebidas.setLayout(jp_bebidasLayout);
        jp_bebidasLayout.setHorizontalGroup(
            jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_bebidasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_agua, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(bt_vinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_cola, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(bt_sumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jp_bebidasLayout.setVerticalGroup(
            jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bebidasLayout.createSequentialGroup()
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_agua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sumo)
                    .addComponent(bt_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bt_bolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_bolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_bolo.setText("Bolo");
        bt_bolo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_bolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_bolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_bolo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_bolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_boloMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jp_pastelariaLayout = new javax.swing.GroupLayout(jp_pastelaria);
        jp_pastelaria.setLayout(jp_pastelariaLayout);
        jp_pastelariaLayout.setHorizontalGroup(
            jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pastelariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pastelariaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jp_bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_pastelariaLayout.createSequentialGroup()
                        .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_pizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_mista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_salgado, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(bt_folhado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_sandes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_bolo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jp_pastelariaLayout.setVerticalGroup(
            jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pastelariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_salgado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_mista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_pastelariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_sandes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_pastelariaLayout.createSequentialGroup()
                        .addComponent(bt_folhado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_bebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        bt_adicionar.setBackground(new java.awt.Color(255, 204, 204));
        bt_adicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_adicionar.setText("Adicionar item");
        bt_adicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_adicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_adicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarActionPerformed(evt);
            }
        });

        bt_menos.setBackground(new java.awt.Color(255, 204, 204));
        bt_menos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_menos.setText("Remover item");
        bt_menos.setActionCommand("-");
        bt_menos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_menos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_menos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menosActionPerformed(evt);
            }
        });

        bt_quantidade.setBackground(new java.awt.Color(255, 204, 204));
        bt_quantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_quantidade.setText("Quantidade");
        bt_quantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_quantidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_quantidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quantidadeActionPerformed(evt);
            }
        });

        bt_remover.setBackground(new java.awt.Color(255, 204, 204));
        bt_remover.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_remover.setText("Remover");
        bt_remover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_remover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_remover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerActionPerformed(evt);
            }
        });

        bt_pagamentos.setBackground(new java.awt.Color(255, 204, 204));
        bt_pagamentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_pagamentos.setText("Pagamentos");
        bt_pagamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_pagamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_pagamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_pagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pagamentosActionPerformed(evt);
            }
        });

        bt_imprimir.setBackground(new java.awt.Color(255, 204, 204));
        bt_imprimir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Untitled-8.gif"))); // NOI18N
        bt_imprimir.setText("Imprimir");
        bt_imprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bt_imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("       Número do pedido");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_pedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_pedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Descrição");

        list_descricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_descricaoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(list_descricao);

        list_qtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_qtdMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(list_qtd);

        list_preco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_precoMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(list_preco);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Qtd");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Valor");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Total");

        list_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_totalMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(list_total);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel21)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel24)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel18)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel19))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel23)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Total");

        bt_novo.setBackground(new java.awt.Color(255, 204, 204));
        bt_novo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_novo.setText("Novo");
        bt_novo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Numerário");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Troco");

        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setToolTipText("");
        lbl_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_totalMouseReleased(evt);
            }
        });

        lbl_numerario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_numerario.setToolTipText("");
        lbl_numerario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_troco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_troco.setToolTipText("");
        lbl_troco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numerario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lbl_numerario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_imprimir)
                    .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(bt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_pagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_imprimir)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_pastelaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_cafeteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jp_cafeteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_pastelaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quantidadeActionPerformed
        // TODO add your handling code here:
        if(list_descricao.getSelectedIndex()<0){
           JOptionPane.showMessageDialog(null,
                    "Deve selecionar um item.", "Quantidade",
                    JOptionPane.ERROR_MESSAGE); 
            return;
        }
        int qtd=0;
        try{
            qtd=Integer.parseInt(JOptionPane.showInputDialog(this,"Digite a quantidade: "));
            if(qtd<=0){
                JOptionPane.showMessageDialog(this,"Quantidade Inválida",
                        "POS",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Verifique os Dados",
                    "POS", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=list_descricao.getSelectedIndex();
        list_qtd.setSelectedIndex(posicao);
        int new_qtd=list_qtd.getSelectedValue()+qtd;
        quantidade.setElementAt(new_qtd,posicao);
        
        list_preco.setSelectedIndex(posicao);
        float prc=list_preco.getSelectedValue();
        list_total.setSelectedIndex(posicao);
        total.setElementAt(Moeda.format(new_qtd*prc), posicao);
        
        total_pedido+=(prc*qtd);
        lbl_total.setText(Moeda.format(total_pedido));
        
        list_descricao.setSelectedIndex(list_qtd.getSelectedIndex());
    }//GEN-LAST:event_bt_quantidadeActionPerformed

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed
        // TODO add your handling code here:
        if(list_descricao.getSelectedIndex()<0){
           JOptionPane.showMessageDialog(null,
                    "Deve selecionar um item.", "Quantidade",
                    JOptionPane.ERROR_MESSAGE); 
            return;
        }
        int qtd=0;
        try{
            qtd=Integer.parseInt(JOptionPane.showInputDialog(this,"Digite a quantidade: "));
            if(qtd<=0 || qtd>list_qtd.getSelectedValue()){
                JOptionPane.showMessageDialog(this,"Quantidade Inválida.",
                        "POS",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Verifique os Dados",
                    "POS", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=list_descricao.getSelectedIndex();
        list_qtd.setSelectedIndex(posicao);
        int new_qtd=list_qtd.getSelectedValue()-qtd;
        quantidade.setElementAt(new_qtd,posicao);
        
        list_preco.setSelectedIndex(posicao);
        float prc=list_preco.getSelectedValue();
        list_total.setSelectedIndex(posicao);
        total.setElementAt(Moeda.format(new_qtd*prc), posicao);
        
        total_pedido-=(prc*qtd);
        lbl_total.setText(Moeda.format(total_pedido ));
       
        
        list_descricao.setSelectedIndex(list_qtd.getSelectedIndex());
        
        if (new_qtd==0){
            descricao.remove(list_descricao.getSelectedIndex());
            quantidade.remove(list_qtd.getSelectedIndex());
            preco.remove(list_preco.getSelectedIndex());
            total.remove(list_total.getSelectedIndex());
        }
    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_pagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pagamentosActionPerformed
        if (list_descricao.getModel().getSize()==0){
            JOptionPane.showMessageDialog(null,
                    "Não existem itens adicionados.", "Pagamento",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        float recebido=0;
        try{
            recebido=Float.parseFloat(JOptionPane.showInputDialog(this,
                    "Digite o valor entregue a pagamento:"));
            if(recebido<total_pedido){
                JOptionPane.showMessageDialog(this,
                        "Valor Insuficiente", "POS",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this,
                        "Dígito Inválido", "POS",
                        JOptionPane.ERROR_MESSAGE);
                return; 
        }
        lbl_numerario.setText(Moeda.format(recebido));
        lbl_troco.setText(Moeda.format(recebido-total_pedido));
        
        Desabilita_Botoes();
        Desabilitar_Paineis();
        
        bt_imprimir.setEnabled(true);
        
    }//GEN-LAST:event_bt_pagamentosActionPerformed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        PrinterJob J=PrinterJob.getPrinterJob();
        J.setPrintable(new Imprimir());
        J.printDialog();
        try{
            J.print();
                        
        }
        
        catch(PrinterException e){
            JOptionPane.showMessageDialog(this,"Erro ao Imprimir",
                    "POS",JOptionPane.ERROR_MESSAGE); 
        }
        
         // guardar na base de dados
        LigacaoMySql bd=new LigacaoMySql();
        try{
            Connection Cn=bd.CriarLigacaoMySql();
            Statement st=Cn.createStatement();
            st.executeUpdate("insert into pedidos (id_pedidos,valor) " +
            "values ('"+lbl_pedido.getText()+"','"+total_pedido+"')");
            
            Clear_All();
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this, 
                    "Erro ao guardar o registo","POS",
                     JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_bt_imprimirActionPerformed
    }
    private void Clear_All(){
            total_pedido=0;
            descricao.clear();
            quantidade.clear();
            preco.clear();
            total.clear();
            lbl_total.setText("");
            lbl_numerario.setText("");
            lbl_troco.setText("");
            lbl_pedido.setText("");
            
            bt_novo.setText("Novo");
            bt_imprimir.setEnabled(false);
    }
    
    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        // TODO add your handling code here:
        if (bt_novo.getText().equals("Novo")){
            
        GregorianCalendar C=new GregorianCalendar();
        int dia=C.get(Calendar.DAY_OF_MONTH);
        int mes=C.get(Calendar.MONTH);
        int ano=C.get(Calendar.YEAR);
        
        int hora=C.get(Calendar.HOUR_OF_DAY);
        int minuto=C.get(Calendar.MINUTE);
        int segundo=C.get(Calendar.SECOND);
        
        lbl_pedido.setText(Integer.toString(dia)+
                           Integer.toString(mes)+
                           Integer.toString(ano)+
                           Integer.toString(hora)+
                           Integer.toString(minuto)+
                           Integer.toString(segundo));
        bt_novo.setText("Cancelar");
        Habilitar_Paineis();
        }
        else{
            bt_novo.setText("Novo");
            lbl_pedido.setText("");
            Desabilitar_Paineis();
            Clear_All();
        }
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarActionPerformed
        if (list_descricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(null,
                    "Não existem itens adicionados.", "Adicionar Produto",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=list_descricao.getSelectedIndex();
        list_qtd.setSelectedIndex(posicao);
        int qtd=list_qtd.getSelectedValue()+1;
        quantidade.setElementAt(qtd, posicao);
        
        list_preco.setSelectedIndex(posicao);
        float wpreco=list_preco.getSelectedValue();
        list_total.setSelectedIndex(posicao);
        total.setElementAt(Moeda.format(qtd*wpreco),posicao);
        
        total_pedido +=wpreco;
        lbl_total.setText(Moeda.format(total_pedido));
        
    }//GEN-LAST:event_bt_adicionarActionPerformed

    private void bt_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menosActionPerformed
        if (list_descricao.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(null,
                    "Não existem itens adicionados.", "Remover Produto",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        int posicao=list_descricao.getSelectedIndex();
        list_qtd.setSelectedIndex(posicao);
        int qtd=list_qtd.getSelectedValue()-1;
        quantidade.setElementAt(qtd, posicao);
        
        list_preco.setSelectedIndex(posicao);
        float wpreco=(list_preco.getSelectedValue());
        list_total.setSelectedIndex(posicao);
        total.setElementAt(qtd*wpreco, posicao);
        
        total_pedido -=wpreco;
        lbl_total.setText(Moeda.format(total_pedido));
        
        if (qtd==0){
            descricao.remove(list_descricao.getSelectedIndex());
            quantidade.remove(list_qtd.getSelectedIndex());
            preco.remove(list_preco.getSelectedIndex());
            total.remove(list_total.getSelectedIndex());
        }
        if(descricao.getSize()==0){
            Desabilita_Botoes();
        }
    }//GEN-LAST:event_bt_menosActionPerformed

    private void bt_cafeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cafeMouseReleased
            AdicionarProduto("Café", 0.8f);
            
    }//GEN-LAST:event_bt_cafeMouseReleased

    private void bt_capuccinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_capuccinoMouseReleased
            AdicionarProduto("Cappucino", 1.6f);
 
    }//GEN-LAST:event_bt_capuccinoMouseReleased

    private void bt_descafeinadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_descafeinadoMouseReleased
            AdicionarProduto("Descafeinado", 0.75f);
    }//GEN-LAST:event_bt_descafeinadoMouseReleased

    private void bt_cariocaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cariocaMouseReleased
            AdicionarProduto("Carioca", 1.0f);
    }//GEN-LAST:event_bt_cariocaMouseReleased

    private void bt_galaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_galaoMouseReleased
            AdicionarProduto("Galão", 1.2f);
    }//GEN-LAST:event_bt_galaoMouseReleased

    private void bt_garotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_garotoMouseReleased
            AdicionarProduto("Garoto", 0.9f);
    }//GEN-LAST:event_bt_garotoMouseReleased

    private void bt_mistaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mistaMouseReleased
            AdicionarProduto("Mista", 2.2f);
    }//GEN-LAST:event_bt_mistaMouseReleased

    private void bt_salgadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salgadoMouseReleased
            AdicionarProduto("Salgado", 1.8f);
    }//GEN-LAST:event_bt_salgadoMouseReleased

    private void bt_pizzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pizzaMouseReleased
            AdicionarProduto("Pizza", 2.9f);
    }//GEN-LAST:event_bt_pizzaMouseReleased

    private void bt_folhadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_folhadoMouseReleased
            AdicionarProduto("Folhado", 1.8f);
    }//GEN-LAST:event_bt_folhadoMouseReleased

    private void bt_sandesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sandesMouseReleased
            AdicionarProduto("Sandes", 1.9f);
    }//GEN-LAST:event_bt_sandesMouseReleased

    private void bt_aguaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_aguaMouseReleased
            AdicionarProduto("Água", 0.5f);
    }//GEN-LAST:event_bt_aguaMouseReleased

    private void bt_colaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colaMouseReleased
            AdicionarProduto("Cola", 1.5f);
    }//GEN-LAST:event_bt_colaMouseReleased

    private void bt_vinhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vinhoMouseReleased
            AdicionarProduto("Vinho", 4.5f);
        
    }//GEN-LAST:event_bt_vinhoMouseReleased

    private void bt_sumoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sumoMouseReleased
            AdicionarProduto("Sumo",2.2f);
    }//GEN-LAST:event_bt_sumoMouseReleased

    private void list_descricaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_descricaoMouseReleased
        // TODO add your handling code here:
        list_qtd.setSelectedIndex(list_descricao.getSelectedIndex());
        list_preco.setSelectedIndex(list_descricao.getSelectedIndex());
        list_total.setSelectedIndex(list_descricao.getSelectedIndex());
    }//GEN-LAST:event_list_descricaoMouseReleased

    private void list_qtdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_qtdMouseReleased
        // TODO add your handling code here
        list_descricao.setSelectedIndex(list_qtd.getSelectedIndex());
        list_preco.setSelectedIndex(list_qtd.getSelectedIndex());
        list_total.setSelectedIndex(list_qtd.getSelectedIndex());
    }//GEN-LAST:event_list_qtdMouseReleased

    private void list_precoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_precoMouseReleased
        // TODO add your handling code here:
        list_qtd.setSelectedIndex(list_preco.getSelectedIndex());
        list_descricao.setSelectedIndex(list_preco.getSelectedIndex());
        list_total.setSelectedIndex(list_preco.getSelectedIndex());
    }//GEN-LAST:event_list_precoMouseReleased

    private void list_totalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_totalMouseReleased
        // TODO add your handling code here:
        list_qtd.setSelectedIndex(list_total.getSelectedIndex());
        list_preco.setSelectedIndex(list_total.getSelectedIndex());
        list_descricao.setSelectedIndex(list_total.getSelectedIndex());
    }//GEN-LAST:event_list_totalMouseReleased

    private void lbl_totalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_totalMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_totalMouseReleased

    private void bt_boloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_boloMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_boloMouseReleased
    private void AdicionarProduto(String NomeProduto, float PrecoProduto) {
        try{
            int posicao=list_descricao.getNextMatch(NomeProduto,
                    0, Position.Bias.Forward);
                    list_qtd.setSelectedIndex(posicao);
                    int qtd = list_qtd.getSelectedValue()+1;
                    quantidade.setElementAt(qtd, posicao);
                    
                    list_total.setSelectedIndex(posicao);
                    total.setElementAt(qtd*PrecoProduto, posicao);
                    
                    total_pedido+=PrecoProduto;
                    lbl_total.setText(Moeda.format(total_pedido));
                    
                    list_descricao.setSelectedIndex(posicao);
                    list_preco.setSelectedIndex(posicao);
                    return;
            }
        catch(Exception e){
            
        descricao.addElement(NomeProduto);
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_qtd.setModel(quantidade);
        
        preco.addElement(PrecoProduto);
        list_preco.setModel(preco);
        
        total.addElement(PrecoProduto);
        list_total.setModel(total);
        
        total_pedido+=PrecoProduto;
        lbl_total.setText(Moeda.format(total_pedido));
        Habilita_Botoes();
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JLabel bt_agua;
    private javax.swing.JLabel bt_bolo;
    private javax.swing.JLabel bt_cafe;
    private javax.swing.JLabel bt_capuccino;
    private javax.swing.JLabel bt_carioca;
    private javax.swing.JLabel bt_cola;
    private javax.swing.JLabel bt_descafeinado;
    private javax.swing.JLabel bt_folhado;
    private javax.swing.JLabel bt_galao;
    private javax.swing.JLabel bt_garoto;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JButton bt_menos;
    private javax.swing.JLabel bt_mista;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_pagamentos;
    private javax.swing.JLabel bt_pizza;
    private javax.swing.JButton bt_quantidade;
    private javax.swing.JButton bt_remover;
    private javax.swing.JLabel bt_salgado;
    private javax.swing.JLabel bt_sandes;
    private javax.swing.JLabel bt_sumo;
    private javax.swing.JLabel bt_vinho;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jp_bebidas;
    private javax.swing.JPanel jp_cafeteria;
    private javax.swing.JPanel jp_pastelaria;
    private javax.swing.JLabel lbl_numerario;
    private javax.swing.JLabel lbl_pedido;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_troco;
    private javax.swing.JList<String> list_descricao;
    private javax.swing.JList<Float> list_preco;
    private javax.swing.JList<Integer> list_qtd;
    private javax.swing.JList<String> list_total;
    // End of variables declaration//GEN-END:variables
}
